// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using MeetingMinutes.DAL.Entities;
using Microsoft.EntityFrameworkCore;
using Action = MeetingMinutes.DAL.Entities.Action;

namespace MeetingMinutes.DAL;

public partial class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Action> Actions { get; set; }

    public virtual DbSet<Item> Items { get; set; }

    public virtual DbSet<ItemStatus> ItemStatuses { get; set; }

    public virtual DbSet<Meeting> Meetings { get; set; }

    public virtual DbSet<MeetingItem> MeetingItems { get; set; }

    public virtual DbSet<MeetingType> MeetingTypes { get; set; }

    public virtual DbSet<Option> Options { get; set; }

    public virtual DbSet<Question> Questions { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Status> Statuses { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<UserVote> UserVotes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        Seeding.ConfigureModels(modelBuilder);
        modelBuilder.Entity<Action>(entity =>
        {
            entity.HasKey(e => e.ActionId).HasName("PK__Action__FFE3F4D93EF34768");
        });

        modelBuilder.Entity<Item>(entity =>
        {
            entity.HasKey(e => e.ItemId).HasName("PK__Item__727E838BCE9D9243");
        });

        modelBuilder.Entity<ItemStatus>(entity =>
        {
            entity.HasKey(e => e.ItemStatusId).HasName("PK__ItemStat__80C775A3FF110F79");

            entity.HasOne(d => d.Item).WithMany(p => p.ItemStatuses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ItemStatu__ItemI__5812160E");

            entity.HasOne(d => d.Status).WithMany(p => p.ItemStatuses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ItemStatu__Statu__571DF1D5");
        });

        modelBuilder.Entity<Meeting>(entity =>
        {
            entity.HasKey(e => e.MeetingId).HasName("PK__Meeting__E9F9E94CEECEB2FA");

            entity.HasOne(d => d.MeetingType).WithMany(p => p.Meetings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Meeting__Meeting__4E88ABD4");
        });

        modelBuilder.Entity<MeetingItem>(entity =>
        {
            entity.HasKey(e => e.MeetingItemId).HasName("PK__MeetingI__0D29BB38BFC6D13C");

            entity.HasOne(d => d.ActionByNavigation).WithMany(p => p.MeetingItems).HasConstraintName("FK__MeetingIt__Actio__60A75C0F");

            entity.HasOne(d => d.Item).WithMany(p => p.MeetingItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__MeetingIt__ItemI__5EBF139D");

            entity.HasOne(d => d.ItemStatus).WithMany(p => p.MeetingItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__MeetingIt__ItemS__5FB337D6");

            entity.HasOne(d => d.Meeting).WithMany(p => p.MeetingItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__MeetingIt__Meeti__5DCAEF64");
        });

        modelBuilder.Entity<MeetingType>(entity =>
        {
            entity.HasKey(e => e.MeetingTypeId).HasName("PK__MeetingT__D161C3E3ED0E7E97");
        });

        modelBuilder.Entity<Option>(entity =>
        {
            entity.HasKey(e => e.OptionId).HasName("PK__Option__92C7A1FF80E2C0C9");

            entity.HasOne(d => d.Question).WithMany(p => p.Options)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Option__Question__2F10007B");
        });

        modelBuilder.Entity<Question>(entity =>
        {
            entity.HasKey(e => e.QuestionId).HasName("PK__Question__0DC06FAC03850C2E");

            entity.HasOne(d => d.User).WithMany(p => p.Questions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Question__UserId__2C3393D0");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Role__8AFACE1ABCEE635E");
        });

        modelBuilder.Entity<Status>(entity =>
        {
            entity.HasKey(e => e.StatusId).HasName("PK__Status__C8EE2063F07396AF");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__User__1788CC4CB9D9A9F3");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => e.UserRoleId).HasName("PK__UserRole__3D978A35AF01185A");

            entity.HasOne(d => d.Role).WithMany(p => p.UserRoles)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserRole__RoleId__29572725");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoles)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserRole__UserId__286302EC");
        });

        modelBuilder.Entity<UserVote>(entity =>
        {
            entity.HasKey(e => e.UserVoteId).HasName("PK__UserVote__0F0C36ECDCE8DEB5");

            entity.HasOne(d => d.Option).WithMany(p => p.UserVotes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserVote__Option__33D4B598");

            entity.HasOne(d => d.Question).WithMany(p => p.UserVotes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserVote__Questi__32E0915F");

            entity.HasOne(d => d.User).WithMany(p => p.UserVotes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserVote__UserId__31EC6D26");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}