// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LetsPollPeople.DAL.Entities;

public partial class Option
{
    [Key]
    public int OptionId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string OptionText { get; set; }

    public int QuestionId { get; set; }

    [ForeignKey("QuestionId")]
    [InverseProperty("Option")]
    public virtual Question Question { get; set; }

    [InverseProperty("Option")]
    public virtual ICollection<UserVote> UserVote { get; set; } = new List<UserVote>();
}