// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LetsPollPeople.DAL.Entities;

public partial class Question
{
    [Key]
    public int QuestionId { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string QuestionText { get; set; }

    public int UserId { get; set; }

    [InverseProperty("Question")]
    public virtual ICollection<Option> Option { get; set; } = new List<Option>();

    [ForeignKey("UserId")]
    [InverseProperty("Question")]
    public virtual User User { get; set; }

    [InverseProperty("Question")]
    public virtual ICollection<UserVote> UserVote { get; set; } = new List<UserVote>();
}