// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LetsPollPeople.DAL.Entities;

public partial class User
{
    [Key]
    public int UserId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Username { get; set; }

    [Required]
    [StringLength(256)]
    [Unicode(false)]
    public string Password { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string LastName { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<UserRole> UserRole { get; set; } = new List<UserRole>();
}