// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MeetingMinutes.DAL.Entities;

[Table("ItemStatus")]
[Index("ItemId", Name = "IX_ItemStatus_ItemId")]
[Index("StatusId", Name = "IX_ItemStatus_StatusId")]
public partial class ItemStatus
{
    [Key]
    public int ItemStatusId { get; set; }

    public int StatusId { get; set; }

    public int ItemId { get; set; }

    [ForeignKey("ItemId")]
    [InverseProperty("ItemStatuses")]
    public virtual Item Item { get; set; }

    [InverseProperty("ItemStatus")]
    public virtual ICollection<MeetingItem> MeetingItems { get; set; } = new List<MeetingItem>();

    [ForeignKey("StatusId")]
    [InverseProperty("ItemStatuses")]
    public virtual Status Status { get; set; }
}