// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MeetingMinutes.DAL.Entities;

[Table("MeetingType")]
[Index("Code", Name = "UQ__MeetingT__A25C5AA7F48E1B23", IsUnique = true)]
public partial class MeetingType
{
    [Key]
    public int MeetingTypeId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Code { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Name { get; set; }

    [InverseProperty("MeetingType")]
    public virtual ICollection<Meeting> Meetings { get; set; } = new List<Meeting>();
}