// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MeetingMinutes.DAL.Entities;

[Table("MeetingItem")]
[Index("ActionBy", Name = "IX_MeetingItem_ActionBy")]
[Index("ItemId", Name = "IX_MeetingItem_ItemId")]
[Index("ItemStatusId", Name = "IX_MeetingItem_ItemStatusId")]
[Index("MeetingId", Name = "IX_MeetingItem_MeetingId")]
public partial class MeetingItem
{
    [Key]
    public int MeetingItemId { get; set; }

    public int MeetingId { get; set; }

    public int ItemId { get; set; }

    public int ItemStatusId { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string Comment { get; set; }

    public int? ActionBy { get; set; }

    [ForeignKey("ActionBy")]
    [InverseProperty("MeetingItems")]
    public virtual User ActionByNavigation { get; set; }

    [ForeignKey("ItemId")]
    [InverseProperty("MeetingItems")]
    public virtual Item Item { get; set; }

    [ForeignKey("ItemStatusId")]
    [InverseProperty("MeetingItems")]
    public virtual ItemStatus ItemStatus { get; set; }

    [ForeignKey("MeetingId")]
    [InverseProperty("MeetingItems")]
    public virtual Meeting Meeting { get; set; }
}