// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MeetingMinutes.DAL.Entities;

[Table("User")]
public partial class User
{
    [Key]
    public int UserId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Username { get; set; }

    [Required]
    [StringLength(256)]
    [Unicode(false)]
    public string Password { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string LastName { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("ActionByNavigation")]
    public virtual ICollection<MeetingItem> MeetingItems { get; set; } = new List<MeetingItem>();

    [InverseProperty("User")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    [InverseProperty("User")]
    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();

    [InverseProperty("User")]
    public virtual ICollection<UserVote> UserVotes { get; set; } = new List<UserVote>();
}