// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Bidvest.Shared.Models;

[Table("Action")]
public partial class ActionModel
{
    [Key]
    public int ActionId { get; set; }

    public bool IsDone { get; set; }

    [Required]
    public string Todo { get; set; }

    public int ItemId { get; set; }
    public virtual ItemModel Item { get; set; }
}