// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Bidvest.Shared.Models;
public partial class ItemStatusModel
{
    [Key]
    public int ItemStatusId { get; set; }

    public int StatusId { get; set; }

    public int ItemId { get; set; }

    public virtual StatusModel Status { get; set; }
}