// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Bidvest.Shared.Models;

[Table("Item")]
public partial class ItemModel
{
    [Key]
    public int ItemId { get; set; }

    [Required]
    public string Name { get; set; }

    [Required]
    public string Description { get; set; }

    public virtual List<ActionModel> Actions { get; set; } = new List<ActionModel>();

    public virtual List<ItemStatusModel> ItemStatuses { get; set; } = new List<ItemStatusModel>();

}