// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using LetsPollPeople.DAL.Entities;
using Microsoft.EntityFrameworkCore;

namespace LetsPollPeople.DAL;

public partial class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Option> Option { get; set; }

    public virtual DbSet<Question> Question { get; set; }

    public virtual DbSet<Role> Role { get; set; }

    public virtual DbSet<User> User { get; set; }

    public virtual DbSet<UserRole> UserRole { get; set; }

    public virtual DbSet<UserVote> UserVote { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Option>(entity =>
        {
            entity.HasKey(e => e.OptionId).HasName("PK__Option__92C7A1FF80E2C0C9");

            entity.HasOne(d => d.Question).WithMany(p => p.Option)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Option__Question__2F10007B");
        });

        modelBuilder.Entity<Question>(entity =>
        {
            entity.HasKey(e => e.QuestionId).HasName("PK__Question__0DC06FAC03850C2E");

            entity.HasOne(d => d.User).WithMany(p => p.Question)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Question__UserId__2C3393D0");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Role__8AFACE1ABCEE635E");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__User__1788CC4CB9D9A9F3");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => e.UserRoleId).HasName("PK__UserRole__3D978A35AF01185A");

            entity.HasOne(d => d.Role).WithMany(p => p.UserRole)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserRole__RoleId__29572725");

            entity.HasOne(d => d.User).WithMany(p => p.UserRole)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserRole__UserId__286302EC");
        });

        modelBuilder.Entity<UserVote>(entity =>
        {
            entity.HasKey(e => e.UserVoteId).HasName("PK__UserVote__0F0C36ECDCE8DEB5");

            entity.HasOne(d => d.Option).WithMany(p => p.UserVote)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserVote__Option__33D4B598");

            entity.HasOne(d => d.Question).WithMany(p => p.UserVote)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserVote__Questi__32E0915F");

            entity.HasOne(d => d.User).WithMany(p => p.UserVote)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserVote__UserId__31EC6D26");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}