// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LetsPollPeople.Shared.Models;

public class UserModel
{
    /// <summary>
    /// UserId is zero when added. Value is above zero for edit
    /// UserId == 0 for Add
    /// UserId >  0 for Edit
    /// </summary>
    public int UserId { get; set; }

    /// <summary>
    /// The username must be unique.
    /// You are required to enter a username
    /// </summary>
    [Required(ErrorMessage = "Required *")]
    [MaxLength(50, ErrorMessage = "Length exceeds 25 for Username")]
    public string Username { get; set; }

    /// <summary>
    /// The password is a sha256 Hash Key.
    /// You are required to enter the password.
    /// Length musn't exceed 25 for password
    /// </summary>
    [Required(ErrorMessage = "Required *")]
    [MinLength(5,  ErrorMessage = "Length must be more than 5 for Password")]
    [MaxLength(25, ErrorMessage = "Length exceeds 25 for Password")]
    public string Password { get; set; }

    [Display(Name = "Confirm Password")]
    [Compare(nameof(Password))]
    public string ConfirmPassword {  get; set; }

    /// <summary>
    /// First name is optional in the Db. It is however required in the model
    /// </summary>
    [Display(Name = "Name")]
    [Required(ErrorMessage = "Required *")]
    [MaxLength(150, ErrorMessage = "Length exceeds 150 for Name")]
    public string FirstName { get; set; }

    /// <summary>
    /// Last name is optional in the Db. It is however required in the model
    /// </summary>
    [Display(Name = "Surname")]
    [Required(ErrorMessage = "Required *")]
    [MaxLength(150, ErrorMessage = "Length exceeds 150 for Surname")]
    public string LastName { get; set; }

    public bool IsActive { get; set; }

    public List<RoleModel> Roles { get; set; }

    public UserModel()
    {
        //Normally this would be false - It's set to true to make it easier to mark the assessmenmt
        IsActive = true;
        Roles    = new List<RoleModel>();
    }
}