// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bidvest.DAL.Entities;

[Table("Item")]
public partial class Item
{
    [Key]
    public int ItemId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [StringLength(1000)]
    [Unicode(false)]
    public string Description { get; set; }

    public DateTime DueDate { get; set; }

    public DateTime? DateCompleted { get; set; }

    [InverseProperty("Item")]
    public virtual ICollection<Action> Actions { get; set; } = new List<Action>();

    [InverseProperty("Item")]
    public virtual ICollection<ItemStatus> ItemStatuses { get; set; } = new List<ItemStatus>();

    [InverseProperty("Item")]
    public virtual ICollection<MeetingItem> MeetingItems { get; set; } = new List<MeetingItem>();
}