// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bidvest.DAL.Entities;

[Table("Meeting")]
[Index("MeetingTypeId", Name = "IX_Meeting_MeetingTypeId")]
[Index("Code", Name = "UQ__Meeting__A25C5AA7CC51BAC9", IsUnique = true)]
public partial class Meeting
{
    [Key]
    public int MeetingId { get; set; }

    public int MeetingTypeId { get; set; }

    public int SequenceNo { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Code { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateCreated { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ScheduleStartDateTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ScheduleEndDateTime { get; set; }

    public int? MinuteDuration { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Title { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string Description { get; set; }

    public int CreatedBy { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("Meeting")]
    public virtual ICollection<MeetingItem> MeetingItems { get; set; } = new List<MeetingItem>();

    [ForeignKey("MeetingTypeId")]
    [InverseProperty("Meetings")]
    public virtual MeetingType MeetingType { get; set; }
}