// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bidvest.DAL.Entities;

[Table("Status")]
[Index("StatusName", Name = "UQ__Status__05E7698AF7684F36", IsUnique = true)]
public partial class Status
{
    [Key]
    public int StatusId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string StatusName { get; set; }

    public bool IsDefaultStatus { get; set; }

    public bool IsCompleteStatus {  get; set; }

    public bool IsDeleted {  get; set; }

    [InverseProperty("Status")]
    public virtual ICollection<ItemStatus> ItemStatuses { get; set; } = new List<ItemStatus>();
}