// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bidvest.DAL.Entities;

[Table("UserVote")]
[Index("OptionId", Name = "IX_UserVote_OptionId")]
[Index("QuestionId", Name = "IX_UserVote_QuestionId")]
[Index("UserId", Name = "IX_UserVote_UserId")]
public partial class UserVote
{
    [Key]
    public int UserVoteId { get; set; }

    public int UserId { get; set; }

    public int QuestionId { get; set; }

    public int OptionId { get; set; }

    [ForeignKey("OptionId")]
    [InverseProperty("UserVotes")]
    public virtual Option Option { get; set; }

    [ForeignKey("QuestionId")]
    [InverseProperty("UserVotes")]
    public virtual Question Question { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserVotes")]
    public virtual User User { get; set; }
}