// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MeetingMinutes.Shared.Models;

public partial class MeetingTypeModel
{
    [Key]
    public int MeetingTypeId { get; set; }

    [Required]
    public string Code { get; set; }

    [Required]
    public string Name { get; set; }

}