// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MeetingMinutes.Shared.Models;

public partial class MeetingModel
{
    [Key]
    public int MeetingId { get; set; }

    public int MeetingTypeId { get; set; }

    public int SequenceNo { get; set; }

    [Required]
    public string Code { get; set; }

    public DateTime DateCreated { get; set; }

    public DateTime ScheduleStartDateTime { get; set; }

    public DateTime ScheduleEndDateTime { get; set; }

    public int? MinuteDuration { get; set; }

    [Required]
    public string Title { get; set; }

    [Required]
    public string Description { get; set; }

    public int CreatedBy { get; set; }

    public virtual MeetingTypeModel MeetingType { get; set; }
}