// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MeetingMinutes.Shared.Models;

public partial class StatusModel
{
    [Key]
    public int StatusId { get; set; }

    [Required]
    public string StatusName { get; set; }

    public bool IsDefaultStatus { get; set; }
}